title: Dan's Blog
email: itsdanli@protonmail.com
description: >- 
  Personal blog to discuss what I'm working on.
baseurl: "/dan_blog"
url: "https://itsdanli.github.io/dan_blog/" 
twitter_username: itsdanli
github_username:  itsdanli

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true