title: Dan Li
email: itsdanli@protonmail.com
description: >- 
  Personal blog to discuss what I'm working on.
baseurl: ""
url: "http://www.itsdan.li/" 
twitter_username: itsdanli
github_username:  itsdanli

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true